[package]
name = "etcd-client"
version = "0.10.0"
authors = ["The etcd-client Authors <davidli2010@foxmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "An etcd v3 API client"
repository = "https://github.com/etcdv3/etcd-client.git"
homepage = "https://github.com/etcdv3/etcd-client"
documentation = "https://docs.rs/etcd-client/"
keywords = ["etcd", "v3", "api", "client", "async"]

[features]
tls = ["tonic/tls"]
tls-openssl = ["dep:openssl"]
tls-roots = ["tls", "tonic/tls-roots"]
pub-response-field = ["visible"]

[dependencies]
tonic = "0.8.0"
prost = "0.11.0"
tokio = "1.20.1"
tokio-stream = "0.1.9"
tower-service = "0.3.2"
http = "0.2.8"
visible = { version = "0.0.1", optional = true }
openssl = { version = "0.10", optional = true }
tower = "0.4.13"
hyper = { version = "0.14.23", features = ["h2", "client"] }
hyper-openssl = "0.9.2"
async-stream = "0.3.3"

[dev-dependencies]
tokio = { version = "1.20.1", features = ["full"] }

[build-dependencies]
tonic-build = { version = "0.8.0", default-features = false, features = ["prost"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
